export const LIST_OF_COMPLETED_TASKS_IS_EMPTY = 0
export const LIST_OF_NON_COMPLETED_TASKS_IS_EMPTY = 0
export const AMOUNT_OF_SELECTED_TASK_IS_ZERO = 0
export const BULLET_ITEM_LIST_IN_TASK_IS_EMPTY = 0
